# Generated by Django 3.1.7 on 2021-02-24 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 15, 35, 17, 611923), verbose_name='Date Published'),
        ),
    ]
