# Generated by Django 3.1.7 on 2021-02-25 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210224_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructors_title', models.CharField(max_length=200)),
                ('instructos_list', models.TextField()),
            ],
            options={
                'db_table': 'instructors',
            },
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 11, 14, 25, 62254), verbose_name='Date Published'),
        ),
    ]
