# Generated by Django 3.1.7 on 2021-02-25 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210225_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='instructos_list',
            new_name='instructor_list',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='instructors_title',
            new_name='instructor_name',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 11, 26, 23, 836774), verbose_name='Date Published'),
        ),
    ]
