# Generated by Django 3.1.7 on 2021-02-26 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210225_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='tutorial_slug',
            new_name='category_slug',
        ),
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='tutorial_summary',
            new_name='category_summary',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 10, 34, 59, 798424), verbose_name='Date Published'),
        ),
    ]
